# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='wordcard',
            name='user',
        ),
        migrations.AddField(
            model_name='cardgroup',
            name='words',
            field=models.ManyToManyField(to='app.WordCard'),
        ),
        migrations.AlterUniqueTogether(
            name='cardgroup',
            unique_together=set([('user', 'name')]),
        ),
    ]
