# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170406_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgroup',
            name='words',
            field=models.ManyToManyField(blank=True, to='app.WordCard'),
        ),
    ]
