# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170406_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordcard',
            name='first_language',
        ),
        migrations.RemoveField(
            model_name='wordcard',
            name='second_language',
        ),
        migrations.AddField(
            model_name='cardgroup',
            name='first_language',
            field=models.CharField(default='PL', max_length=100),
        ),
        migrations.AddField(
            model_name='cardgroup',
            name='second_language',
            field=models.CharField(default='EN', max_length=100),
        ),
    ]
