# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20170524_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgroup',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardgroup',
            name='users',
            field=models.ManyToManyField(related_name='users_with_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
