# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170525_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardgroup',
            name='public',
        ),
        migrations.AddField(
            model_name='cardgroup',
            name='link',
            field=models.CharField(default='testHash', max_length=30),
            preserve_default=False,
        ),
    ]
