# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170527_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgroup',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
