# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_cardgroup_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardgroup',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='cardgroup',
            unique_together=set([('owner', 'name')]),
        ),
    ]
